// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_v_frmbuf_rd_0_1_MultiPixStream2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_dout,
        img_empty_n,
        img_read,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        Height_dout,
        Height_empty_n,
        Height_read,
        WidthOut_dout,
        WidthOut_empty_n,
        WidthOut_read,
        colorFormat_dout,
        colorFormat_empty_n,
        colorFormat_read
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_pp0_stage0 = 8'd4;
parameter    ap_ST_fsm_state5 = 8'd8;
parameter    ap_ST_fsm_state6 = 8'd16;
parameter    ap_ST_fsm_pp1_stage0 = 8'd32;
parameter    ap_ST_fsm_state9 = 8'd64;
parameter    ap_ST_fsm_state10 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input   img_empty_n;
output   img_read;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [10:0] Height_dout;
input   Height_empty_n;
output   Height_read;
input  [10:0] WidthOut_dout;
input   WidthOut_empty_n;
output   WidthOut_read;
input  [1:0] colorFormat_dout;
input   colorFormat_empty_n;
output   colorFormat_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_read;
reg m_axis_video_TVALID;
reg Height_read;
reg WidthOut_read;
reg colorFormat_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] mapComp_address0;
reg    mapComp_ce0;
wire   [1:0] mapComp_q0;
reg    img_blk_n;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] icmp_ln246_reg_575;
reg    m_axis_video_TDATA_blk_n;
reg    Height_blk_n;
reg    WidthOut_blk_n;
reg    colorFormat_blk_n;
reg   [1:0] i_reg_200;
reg   [10:0] j_reg_223;
reg   [0:0] sof_3_reg_234;
reg   [1:0] colorFormat_read_reg_484;
wire   [10:0] grp_reg_unsigned_short_s_fu_246_ap_return;
reg   [10:0] rows_reg_490;
wire    ap_CS_fsm_state2;
wire   [10:0] grp_reg_unsigned_short_s_fu_252_ap_return;
reg   [10:0] cols_reg_495;
wire   [11:0] zext_ln197_fu_258_p1;
reg   [11:0] zext_ln197_reg_501;
wire   [3:0] sub_ln240_fu_272_p2;
reg   [3:0] sub_ln240_reg_506;
wire   [1:0] add_ln238_fu_278_p2;
reg   [1:0] add_ln238_reg_511;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln238_fu_284_p2;
reg   [0:0] icmp_ln238_reg_516;
wire   [11:0] sub_i_fu_332_p2;
reg   [11:0] sub_i_reg_532;
wire    ap_CS_fsm_state5;
wire   [0:0] cmp26125_i_fu_337_p2;
reg   [0:0] cmp26125_i_reg_537;
wire   [1:0] trunc_ln215_fu_342_p1;
reg   [1:0] trunc_ln215_reg_541;
wire   [1:0] trunc_ln215_1_fu_346_p1;
reg   [1:0] trunc_ln215_1_reg_546;
wire   [1:0] trunc_ln215_2_fu_350_p1;
reg   [1:0] trunc_ln215_2_reg_551;
wire   [10:0] i_2_fu_359_p2;
reg   [10:0] i_2_reg_556;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln244_fu_368_p2;
wire   [10:0] j_1_fu_373_p2;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_state7_pp1_stage0_iter0;
reg    ap_block_state8_pp1_stage0_iter1;
reg    ap_block_state8_io;
reg    ap_block_pp1_stage0_11001;
wire   [0:0] icmp_ln246_fu_383_p2;
wire   [0:0] icmp_ln259_fu_388_p2;
reg   [0:0] icmp_ln259_reg_579;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_flush_enable;
reg   [1:0] ap_phi_mux_i_phi_fu_204_p4;
wire    ap_block_pp0_stage0;
reg   [10:0] i_1_reg_212;
wire    ap_CS_fsm_state9;
wire   [31:0] zext_ln240_3_fu_299_p1;
reg   [4:0] map_V_0_038_i_fu_118;
wire   [4:0] zext_ln240_2_fu_304_p1;
reg   [4:0] map_V_1_039_i_fu_122;
reg   [4:0] map_V_2_040_i_fu_126;
reg   [0:0] sof_fu_130;
reg    ap_block_state1;
reg    ap_block_pp1_stage0_01001;
wire   [3:0] tmp_3_fu_265_p3;
wire   [3:0] zext_ln240_fu_262_p1;
wire   [3:0] zext_ln240_1_fu_290_p1;
wire   [3:0] add_ln240_fu_294_p2;
wire   [11:0] zext_ln246_fu_379_p1;
wire   [7:0] pix_val_V_0_fu_393_p1;
wire   [7:0] tmp_fu_417_p2;
wire   [7:0] tmp_fu_417_p3;
wire   [7:0] tmp_1_fu_428_p2;
wire   [7:0] tmp_1_fu_428_p3;
wire   [7:0] tmp_2_fu_439_p2;
wire   [7:0] tmp_2_fu_439_p3;
wire   [7:0] tmp_2_fu_439_p5;
wire   [7:0] tmp_1_fu_428_p5;
wire   [7:0] tmp_fu_417_p5;
wire    ap_CS_fsm_state10;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

system_v_frmbuf_rd_0_1_MultiPixStream2AXIvideo_mapComp #(
    .DataWidth( 2 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
mapComp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mapComp_address0),
    .ce0(mapComp_ce0),
    .q0(mapComp_q0)
);

system_v_frmbuf_rd_0_1_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_246(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(Height_dout),
    .ap_return(grp_reg_unsigned_short_s_fu_246_ap_return)
);

system_v_frmbuf_rd_0_1_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_252(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(WidthOut_dout),
    .ap_return(grp_reg_unsigned_short_s_fu_252_ap_return)
);

system_v_frmbuf_rd_0_1_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U32(
    .din0(pix_val_V_0_fu_393_p1),
    .din1(tmp_fu_417_p2),
    .din2(tmp_fu_417_p3),
    .din3(trunc_ln215_reg_541),
    .dout(tmp_fu_417_p5)
);

system_v_frmbuf_rd_0_1_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U33(
    .din0(pix_val_V_0_fu_393_p1),
    .din1(tmp_1_fu_428_p2),
    .din2(tmp_1_fu_428_p3),
    .din3(trunc_ln215_1_reg_546),
    .dout(tmp_1_fu_428_p5)
);

system_v_frmbuf_rd_0_1_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U34(
    .din0(pix_val_V_0_fu_393_p1),
    .din1(tmp_2_fu_439_p2),
    .din2(tmp_2_fu_439_p3),
    .din3(trunc_ln215_2_reg_551),
    .dout(tmp_2_fu_439_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln244_fu_368_p2 == 1'd0) & (cmp26125_i_reg_537 == 1'd0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln244_fu_368_p2 == 1'd0) & (cmp26125_i_reg_537 == 1'd0))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_1_reg_212 <= i_2_reg_556;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        i_1_reg_212 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln238_reg_516 == 1'd0))) begin
        i_reg_200 <= add_ln238_reg_511;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_200 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln244_fu_368_p2 == 1'd0) & (cmp26125_i_reg_537 == 1'd0))) begin
        j_reg_223 <= 11'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln246_fu_383_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        j_reg_223 <= j_1_fu_373_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln244_fu_368_p2 == 1'd0) & (cmp26125_i_reg_537 == 1'd0))) begin
        sof_3_reg_234 <= sof_fu_130;
    end else if (((icmp_ln246_reg_575 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        sof_3_reg_234 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sof_fu_130 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state9) & (cmp26125_i_reg_537 == 1'd0))) begin
        sof_fu_130 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        add_ln238_reg_511 <= add_ln238_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cmp26125_i_reg_537 <= cmp26125_i_fu_337_p2;
        sub_i_reg_532 <= sub_i_fu_332_p2;
        trunc_ln215_1_reg_546 <= trunc_ln215_1_fu_346_p1;
        trunc_ln215_2_reg_551 <= trunc_ln215_2_fu_350_p1;
        trunc_ln215_reg_541 <= trunc_ln215_fu_342_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        colorFormat_read_reg_484 <= colorFormat_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cols_reg_495 <= grp_reg_unsigned_short_s_fu_252_ap_return;
        rows_reg_490 <= grp_reg_unsigned_short_s_fu_246_ap_return;
        sub_ln240_reg_506 <= sub_ln240_fu_272_p2;
        zext_ln197_reg_501[10 : 0] <= zext_ln197_fu_258_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_2_reg_556 <= i_2_fu_359_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln238_reg_516 <= icmp_ln238_fu_284_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln246_reg_575 <= icmp_ln246_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln246_fu_383_p2 == 1'd0))) begin
        icmp_ln259_reg_579 <= icmp_ln259_fu_388_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((i_reg_200 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        map_V_0_038_i_fu_118[1 : 0] <= zext_ln240_2_fu_304_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((i_reg_200 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        map_V_1_039_i_fu_122[1 : 0] <= zext_ln240_2_fu_304_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_reg_200 == 2'd1) & ~(i_reg_200 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        map_V_2_040_i_fu_126[1 : 0] <= zext_ln240_2_fu_304_p1[1 : 0];
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((colorFormat_empty_n == 1'b0) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthOut_blk_n = WidthOut_empty_n;
    end else begin
        WidthOut_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((colorFormat_empty_n == 1'b0) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthOut_read = 1'b1;
    end else begin
        WidthOut_read = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln238_fu_284_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln246_fu_383_p2 == 1'd1))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln238_reg_516 == 1'd0))) begin
        ap_phi_mux_i_phi_fu_204_p4 = add_ln238_reg_511;
    end else begin
        ap_phi_mux_i_phi_fu_204_p4 = i_reg_200;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_blk_n = colorFormat_empty_n;
    end else begin
        colorFormat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((colorFormat_empty_n == 1'b0) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_read = 1'b1;
    end else begin
        colorFormat_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln246_reg_575 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_blk_n = img_empty_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln246_reg_575 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_read = 1'b1;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln246_reg_575 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        m_axis_video_TDATA_blk_n = m_axis_video_TREADY;
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln246_reg_575 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        m_axis_video_TVALID = 1'b1;
    end else begin
        m_axis_video_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        mapComp_ce0 = 1'b1;
    end else begin
        mapComp_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((colorFormat_empty_n == 1'b0) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln238_fu_284_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln238_fu_284_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln244_fu_368_p2 == 1'd0) & (cmp26125_i_reg_537 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln244_fu_368_p2 == 1'd0) & (cmp26125_i_reg_537 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln238_fu_278_p2 = (ap_phi_mux_i_phi_fu_204_p4 + 2'd1);

assign add_ln240_fu_294_p2 = (sub_ln240_reg_506 + zext_ln240_1_fu_290_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = ((ap_enable_reg_pp1_iter1 == 1'b1) & (((icmp_ln246_reg_575 == 1'd0) & (m_axis_video_TREADY == 1'b0)) | ((icmp_ln246_reg_575 == 1'd0) & (img_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((ap_enable_reg_pp1_iter1 == 1'b1) & ((1'b1 == ap_block_state8_io) | ((icmp_ln246_reg_575 == 1'd0) & (m_axis_video_TREADY == 1'b0)) | ((icmp_ln246_reg_575 == 1'd0) & (img_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((ap_enable_reg_pp1_iter1 == 1'b1) & ((1'b1 == ap_block_state8_io) | ((icmp_ln246_reg_575 == 1'd0) & (m_axis_video_TREADY == 1'b0)) | ((icmp_ln246_reg_575 == 1'd0) & (img_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((colorFormat_empty_n == 1'b0) | (1'b0 == WidthOut_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((icmp_ln246_reg_575 == 1'd0) & (m_axis_video_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp1_stage0_iter1 = (((icmp_ln246_reg_575 == 1'd0) & (m_axis_video_TREADY == 1'b0)) | ((icmp_ln246_reg_575 == 1'd0) & (img_empty_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign cmp26125_i_fu_337_p2 = ((cols_reg_495 == 11'd0) ? 1'b1 : 1'b0);

assign i_2_fu_359_p2 = (i_1_reg_212 + 11'd1);

assign icmp_ln238_fu_284_p2 = ((ap_phi_mux_i_phi_fu_204_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln244_fu_368_p2 = ((i_1_reg_212 == rows_reg_490) ? 1'b1 : 1'b0);

assign icmp_ln246_fu_383_p2 = ((j_reg_223 == cols_reg_495) ? 1'b1 : 1'b0);

assign icmp_ln259_fu_388_p2 = ((zext_ln246_fu_379_p1 == sub_i_reg_532) ? 1'b1 : 1'b0);

assign j_1_fu_373_p2 = (j_reg_223 + 11'd1);

assign m_axis_video_TDATA = {{{tmp_2_fu_439_p5}, {tmp_1_fu_428_p5}}, {tmp_fu_417_p5}};

assign m_axis_video_TDEST = 1'd0;

assign m_axis_video_TID = 1'd0;

assign m_axis_video_TKEEP = 3'd7;

assign m_axis_video_TLAST = icmp_ln259_reg_579;

assign m_axis_video_TSTRB = 3'd0;

assign m_axis_video_TUSER = sof_3_reg_234;

assign mapComp_address0 = zext_ln240_3_fu_299_p1;

assign pix_val_V_0_fu_393_p1 = img_dout[7:0];

assign sub_i_fu_332_p2 = ($signed(zext_ln197_reg_501) + $signed(12'd4095));

assign sub_ln240_fu_272_p2 = (tmp_3_fu_265_p3 - zext_ln240_fu_262_p1);

assign tmp_1_fu_428_p2 = {{img_dout[15:8]}};

assign tmp_1_fu_428_p3 = {{img_dout[23:16]}};

assign tmp_2_fu_439_p2 = {{img_dout[15:8]}};

assign tmp_2_fu_439_p3 = {{img_dout[23:16]}};

assign tmp_3_fu_265_p3 = {{colorFormat_read_reg_484}, {2'd0}};

assign tmp_fu_417_p2 = {{img_dout[15:8]}};

assign tmp_fu_417_p3 = {{img_dout[23:16]}};

assign trunc_ln215_1_fu_346_p1 = map_V_1_039_i_fu_122[1:0];

assign trunc_ln215_2_fu_350_p1 = map_V_2_040_i_fu_126[1:0];

assign trunc_ln215_fu_342_p1 = map_V_0_038_i_fu_118[1:0];

assign zext_ln197_fu_258_p1 = grp_reg_unsigned_short_s_fu_252_ap_return;

assign zext_ln240_1_fu_290_p1 = ap_phi_mux_i_phi_fu_204_p4;

assign zext_ln240_2_fu_304_p1 = mapComp_q0;

assign zext_ln240_3_fu_299_p1 = add_ln240_fu_294_p2;

assign zext_ln240_fu_262_p1 = colorFormat_read_reg_484;

assign zext_ln246_fu_379_p1 = j_reg_223;

always @ (posedge ap_clk) begin
    zext_ln197_reg_501[11] <= 1'b0;
    map_V_0_038_i_fu_118[4:2] <= 3'b000;
    map_V_1_039_i_fu_122[4:2] <= 3'b000;
    map_V_2_040_i_fu_126[4:2] <= 3'b000;
end

endmodule //system_v_frmbuf_rd_0_1_MultiPixStream2AXIvideo
