Match User 8ax-tunnel
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PermitTTY no
    X11Forwarding no
    AllowAgentForwarding no
    AllowTcpForwarding remote
    GatewayPorts no
    AuthorizedKeysFile none
    AuthorizedKeysCommand /usr/local/libexec/8ax-remote-ssh-authorized-keys %u
    AuthorizedKeysCommandUser z20auth
