Match User 8ax-tunnel
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PermitTTY no
    X11Forwarding no
    AllowAgentForwarding no
    AllowTcpForwarding remote
    GatewayPorts no
    AuthorizedKeysFile /opt/8ax-auth/storage/remote-ssh/authorized_keys
