#ifndef V5_TOOLPATH_VIEWPORT_H
#define V5_TOOLPATH_VIEWPORT_H

#define V5_TOOLPATH_VIEWPORT_X 0
#define V5_TOOLPATH_VIEWPORT_Y 55
#define V5_TOOLPATH_VIEWPORT_WIDTH 394
#define V5_TOOLPATH_VIEWPORT_HEIGHT 386
#define V5_TOOLPATH_VIEWPORT_GESTURE_LEFT_INSET 135
#define V5_TOOLPATH_VIEWPORT_GESTURE_RIGHT_INSET 67
#define V5_TOOLPATH_VIEWPORT_GESTURE_BOTTOM_INSET 63

#define V5_TOOLPATH_RASTER_TILE_SIZE 16U
#define V5_TOOLPATH_RASTER_TILE_COLUMNS \
    ((V5_TOOLPATH_VIEWPORT_WIDTH + (int)V5_TOOLPATH_RASTER_TILE_SIZE - 1) / \
     (int)V5_TOOLPATH_RASTER_TILE_SIZE)
#define V5_TOOLPATH_RASTER_TILE_ROWS \
    ((V5_TOOLPATH_VIEWPORT_HEIGHT + (int)V5_TOOLPATH_RASTER_TILE_SIZE - 1) / \
     (int)V5_TOOLPATH_RASTER_TILE_SIZE)
#define V5_TOOLPATH_RASTER_PIXEL_COUNT \
    (V5_TOOLPATH_VIEWPORT_WIDTH * V5_TOOLPATH_VIEWPORT_HEIGHT)
#define V5_TOOLPATH_RASTER_WORD_COUNT \
    ((V5_TOOLPATH_RASTER_PIXEL_COUNT + 63) / 64)

typedef struct V5ToolpathViewport {
    int x;
    int y;
    int width;
    int height;
    int gesture_left_inset;
    int gesture_right_inset;
    int gesture_bottom_inset;
} V5ToolpathViewport;

static inline const V5ToolpathViewport *v5_toolpath_viewport(void)
{
    static const V5ToolpathViewport viewport = {
        V5_TOOLPATH_VIEWPORT_X,
        V5_TOOLPATH_VIEWPORT_Y,
        V5_TOOLPATH_VIEWPORT_WIDTH,
        V5_TOOLPATH_VIEWPORT_HEIGHT,
        V5_TOOLPATH_VIEWPORT_GESTURE_LEFT_INSET,
        V5_TOOLPATH_VIEWPORT_GESTURE_RIGHT_INSET,
        V5_TOOLPATH_VIEWPORT_GESTURE_BOTTOM_INSET
    };
    return &viewport;
}

#endif
