// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_v_frmbuf_rd_0_2_FrmbufRdHlsDataFlow (
        m_axi_mm_video_AWVALID,
        m_axi_mm_video_AWREADY,
        m_axi_mm_video_AWADDR,
        m_axi_mm_video_AWID,
        m_axi_mm_video_AWLEN,
        m_axi_mm_video_AWSIZE,
        m_axi_mm_video_AWBURST,
        m_axi_mm_video_AWLOCK,
        m_axi_mm_video_AWCACHE,
        m_axi_mm_video_AWPROT,
        m_axi_mm_video_AWQOS,
        m_axi_mm_video_AWREGION,
        m_axi_mm_video_AWUSER,
        m_axi_mm_video_WVALID,
        m_axi_mm_video_WREADY,
        m_axi_mm_video_WDATA,
        m_axi_mm_video_WSTRB,
        m_axi_mm_video_WLAST,
        m_axi_mm_video_WID,
        m_axi_mm_video_WUSER,
        m_axi_mm_video_ARVALID,
        m_axi_mm_video_ARREADY,
        m_axi_mm_video_ARADDR,
        m_axi_mm_video_ARID,
        m_axi_mm_video_ARLEN,
        m_axi_mm_video_ARSIZE,
        m_axi_mm_video_ARBURST,
        m_axi_mm_video_ARLOCK,
        m_axi_mm_video_ARCACHE,
        m_axi_mm_video_ARPROT,
        m_axi_mm_video_ARQOS,
        m_axi_mm_video_ARREGION,
        m_axi_mm_video_ARUSER,
        m_axi_mm_video_RVALID,
        m_axi_mm_video_RREADY,
        m_axi_mm_video_RDATA,
        m_axi_mm_video_RLAST,
        m_axi_mm_video_RID,
        m_axi_mm_video_RUSER,
        m_axi_mm_video_RRESP,
        m_axi_mm_video_BVALID,
        m_axi_mm_video_BREADY,
        m_axi_mm_video_BRESP,
        m_axi_mm_video_BID,
        m_axi_mm_video_BUSER,
        m_axis_video_TDATA,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        HwReg_frm_buffer,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        ap_clk,
        ap_rst,
        HwReg_frm_buffer_ap_vld,
        p_read1_ap_vld,
        p_read4_ap_vld,
        p_read2_ap_vld,
        p_read_ap_vld,
        p_read3_ap_vld,
        p_read5_ap_vld,
        ap_start,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_mm_video_AWVALID;
input   m_axi_mm_video_AWREADY;
output  [31:0] m_axi_mm_video_AWADDR;
output  [0:0] m_axi_mm_video_AWID;
output  [31:0] m_axi_mm_video_AWLEN;
output  [2:0] m_axi_mm_video_AWSIZE;
output  [1:0] m_axi_mm_video_AWBURST;
output  [1:0] m_axi_mm_video_AWLOCK;
output  [3:0] m_axi_mm_video_AWCACHE;
output  [2:0] m_axi_mm_video_AWPROT;
output  [3:0] m_axi_mm_video_AWQOS;
output  [3:0] m_axi_mm_video_AWREGION;
output  [0:0] m_axi_mm_video_AWUSER;
output   m_axi_mm_video_WVALID;
input   m_axi_mm_video_WREADY;
output  [63:0] m_axi_mm_video_WDATA;
output  [7:0] m_axi_mm_video_WSTRB;
output   m_axi_mm_video_WLAST;
output  [0:0] m_axi_mm_video_WID;
output  [0:0] m_axi_mm_video_WUSER;
output   m_axi_mm_video_ARVALID;
input   m_axi_mm_video_ARREADY;
output  [31:0] m_axi_mm_video_ARADDR;
output  [0:0] m_axi_mm_video_ARID;
output  [31:0] m_axi_mm_video_ARLEN;
output  [2:0] m_axi_mm_video_ARSIZE;
output  [1:0] m_axi_mm_video_ARBURST;
output  [1:0] m_axi_mm_video_ARLOCK;
output  [3:0] m_axi_mm_video_ARCACHE;
output  [2:0] m_axi_mm_video_ARPROT;
output  [3:0] m_axi_mm_video_ARQOS;
output  [3:0] m_axi_mm_video_ARREGION;
output  [0:0] m_axi_mm_video_ARUSER;
input   m_axi_mm_video_RVALID;
output   m_axi_mm_video_RREADY;
input  [63:0] m_axi_mm_video_RDATA;
input   m_axi_mm_video_RLAST;
input  [0:0] m_axi_mm_video_RID;
input  [0:0] m_axi_mm_video_RUSER;
input  [1:0] m_axi_mm_video_RRESP;
input   m_axi_mm_video_BVALID;
output   m_axi_mm_video_BREADY;
input  [1:0] m_axi_mm_video_BRESP;
input  [0:0] m_axi_mm_video_BID;
input  [0:0] m_axi_mm_video_BUSER;
output  [23:0] m_axis_video_TDATA;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [31:0] HwReg_frm_buffer;
input  [10:0] p_read;
input  [10:0] p_read1;
input  [15:0] p_read2;
input  [5:0] p_read3;
input  [13:0] p_read4;
input  [1:0] p_read5;
input   ap_clk;
input   ap_rst;
input   HwReg_frm_buffer_ap_vld;
input   p_read1_ap_vld;
input   p_read4_ap_vld;
input   p_read2_ap_vld;
input   p_read_ap_vld;
input   p_read3_ap_vld;
input   p_read5_ap_vld;
input   ap_start;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    AXIMMvideo2Bytes7_U0_ap_start;
wire    AXIMMvideo2Bytes7_U0_start_full_n;
wire    AXIMMvideo2Bytes7_U0_ap_done;
wire    AXIMMvideo2Bytes7_U0_ap_continue;
wire    AXIMMvideo2Bytes7_U0_ap_idle;
wire    AXIMMvideo2Bytes7_U0_ap_ready;
wire    AXIMMvideo2Bytes7_U0_start_out;
wire    AXIMMvideo2Bytes7_U0_start_write;
wire    AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWVALID;
wire   [31:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWADDR;
wire   [0:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWID;
wire   [31:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWLEN;
wire   [2:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWSIZE;
wire   [1:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWBURST;
wire   [1:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWLOCK;
wire   [3:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWCACHE;
wire   [2:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWPROT;
wire   [3:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWQOS;
wire   [3:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWREGION;
wire   [0:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWUSER;
wire    AXIMMvideo2Bytes7_U0_m_axi_mm_video_WVALID;
wire   [63:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_WDATA;
wire   [7:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_WSTRB;
wire    AXIMMvideo2Bytes7_U0_m_axi_mm_video_WLAST;
wire   [0:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_WID;
wire   [0:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_WUSER;
wire    AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARVALID;
wire   [31:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARADDR;
wire   [0:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARID;
wire   [31:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARLEN;
wire   [2:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARSIZE;
wire   [1:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARBURST;
wire   [1:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARLOCK;
wire   [3:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARCACHE;
wire   [2:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARPROT;
wire   [3:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARQOS;
wire   [3:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARREGION;
wire   [0:0] AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARUSER;
wire    AXIMMvideo2Bytes7_U0_m_axi_mm_video_RREADY;
wire    AXIMMvideo2Bytes7_U0_m_axi_mm_video_BREADY;
wire   [63:0] AXIMMvideo2Bytes7_U0_bytePlanes1_din;
wire    AXIMMvideo2Bytes7_U0_bytePlanes1_write;
wire   [10:0] AXIMMvideo2Bytes7_U0_Height_out_din;
wire    AXIMMvideo2Bytes7_U0_Height_out_write;
wire   [13:0] AXIMMvideo2Bytes7_U0_WidthInBytes_out_din;
wire    AXIMMvideo2Bytes7_U0_WidthInBytes_out_write;
wire   [10:0] AXIMMvideo2Bytes7_U0_width_out_din;
wire    AXIMMvideo2Bytes7_U0_width_out_write;
wire   [5:0] AXIMMvideo2Bytes7_U0_video_format_out_din;
wire    AXIMMvideo2Bytes7_U0_video_format_out_write;
wire   [1:0] AXIMMvideo2Bytes7_U0_colorFormat_out_din;
wire    AXIMMvideo2Bytes7_U0_colorFormat_out_write;
wire    Bytes2MultiPixStream_U0_ap_start;
wire    Bytes2MultiPixStream_U0_ap_done;
wire    Bytes2MultiPixStream_U0_ap_continue;
wire    Bytes2MultiPixStream_U0_ap_idle;
wire    Bytes2MultiPixStream_U0_ap_ready;
wire    Bytes2MultiPixStream_U0_bytePlanes1_read;
wire   [23:0] Bytes2MultiPixStream_U0_img_din;
wire    Bytes2MultiPixStream_U0_img_write;
wire    Bytes2MultiPixStream_U0_Height_read;
wire    Bytes2MultiPixStream_U0_Width_read;
wire    Bytes2MultiPixStream_U0_WidthInBytes_read;
wire    Bytes2MultiPixStream_U0_VideoFormat_read;
wire   [10:0] Bytes2MultiPixStream_U0_Height_out_din;
wire    Bytes2MultiPixStream_U0_Height_out_write;
wire   [10:0] Bytes2MultiPixStream_U0_Width_out_din;
wire    Bytes2MultiPixStream_U0_Width_out_write;
wire    MultiPixStream2AXIvideo_U0_ap_start;
wire    MultiPixStream2AXIvideo_U0_ap_done;
wire    MultiPixStream2AXIvideo_U0_ap_continue;
wire    MultiPixStream2AXIvideo_U0_ap_idle;
wire    MultiPixStream2AXIvideo_U0_ap_ready;
wire    MultiPixStream2AXIvideo_U0_img_read;
wire   [23:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;
wire    MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TID;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;
wire    MultiPixStream2AXIvideo_U0_Height_read;
wire    MultiPixStream2AXIvideo_U0_WidthOut_read;
wire    MultiPixStream2AXIvideo_U0_colorFormat_read;
wire    ap_sync_continue;
wire    bytePlanes_plane0_full_n;
wire   [63:0] bytePlanes_plane0_dout;
wire    bytePlanes_plane0_empty_n;
wire    height_c_full_n;
wire   [10:0] height_c_dout;
wire    height_c_empty_n;
wire    WidthInBytes_c_full_n;
wire   [13:0] WidthInBytes_c_dout;
wire    WidthInBytes_c_empty_n;
wire    width_c_full_n;
wire   [10:0] width_c_dout;
wire    width_c_empty_n;
wire    video_format_c_full_n;
wire   [5:0] video_format_c_dout;
wire    video_format_c_empty_n;
wire    colorFormat_c_full_n;
wire   [1:0] colorFormat_c_dout;
wire    colorFormat_c_empty_n;
wire    img_full_n;
wire   [23:0] img_dout;
wire    img_empty_n;
wire    height_c9_full_n;
wire   [10:0] height_c9_dout;
wire    height_c9_empty_n;
wire    width_c10_full_n;
wire   [10:0] width_c10_dout;
wire    width_c10_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_Bytes2MultiPixStream_U0_din;
wire    start_for_Bytes2MultiPixStream_U0_full_n;
wire   [0:0] start_for_Bytes2MultiPixStream_U0_dout;
wire    start_for_Bytes2MultiPixStream_U0_empty_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_din;
wire    start_for_MultiPixStream2AXIvideo_U0_full_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_dout;
wire    start_for_MultiPixStream2AXIvideo_U0_empty_n;
wire    Bytes2MultiPixStream_U0_start_full_n;
wire    Bytes2MultiPixStream_U0_start_write;
wire    MultiPixStream2AXIvideo_U0_start_full_n;
wire    MultiPixStream2AXIvideo_U0_start_write;

system_v_frmbuf_rd_0_2_AXIMMvideo2Bytes7 AXIMMvideo2Bytes7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AXIMMvideo2Bytes7_U0_ap_start),
    .start_full_n(AXIMMvideo2Bytes7_U0_start_full_n),
    .ap_done(AXIMMvideo2Bytes7_U0_ap_done),
    .ap_continue(AXIMMvideo2Bytes7_U0_ap_continue),
    .ap_idle(AXIMMvideo2Bytes7_U0_ap_idle),
    .ap_ready(AXIMMvideo2Bytes7_U0_ap_ready),
    .start_out(AXIMMvideo2Bytes7_U0_start_out),
    .start_write(AXIMMvideo2Bytes7_U0_start_write),
    .m_axi_mm_video_AWVALID(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWVALID),
    .m_axi_mm_video_AWREADY(1'b0),
    .m_axi_mm_video_AWADDR(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWADDR),
    .m_axi_mm_video_AWID(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWID),
    .m_axi_mm_video_AWLEN(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWLEN),
    .m_axi_mm_video_AWSIZE(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWSIZE),
    .m_axi_mm_video_AWBURST(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWBURST),
    .m_axi_mm_video_AWLOCK(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWLOCK),
    .m_axi_mm_video_AWCACHE(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWCACHE),
    .m_axi_mm_video_AWPROT(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWPROT),
    .m_axi_mm_video_AWQOS(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWQOS),
    .m_axi_mm_video_AWREGION(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWREGION),
    .m_axi_mm_video_AWUSER(AXIMMvideo2Bytes7_U0_m_axi_mm_video_AWUSER),
    .m_axi_mm_video_WVALID(AXIMMvideo2Bytes7_U0_m_axi_mm_video_WVALID),
    .m_axi_mm_video_WREADY(1'b0),
    .m_axi_mm_video_WDATA(AXIMMvideo2Bytes7_U0_m_axi_mm_video_WDATA),
    .m_axi_mm_video_WSTRB(AXIMMvideo2Bytes7_U0_m_axi_mm_video_WSTRB),
    .m_axi_mm_video_WLAST(AXIMMvideo2Bytes7_U0_m_axi_mm_video_WLAST),
    .m_axi_mm_video_WID(AXIMMvideo2Bytes7_U0_m_axi_mm_video_WID),
    .m_axi_mm_video_WUSER(AXIMMvideo2Bytes7_U0_m_axi_mm_video_WUSER),
    .m_axi_mm_video_ARVALID(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARVALID),
    .m_axi_mm_video_ARREADY(m_axi_mm_video_ARREADY),
    .m_axi_mm_video_ARADDR(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARADDR),
    .m_axi_mm_video_ARID(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARID),
    .m_axi_mm_video_ARLEN(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARLEN),
    .m_axi_mm_video_ARSIZE(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARSIZE),
    .m_axi_mm_video_ARBURST(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARBURST),
    .m_axi_mm_video_ARLOCK(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARLOCK),
    .m_axi_mm_video_ARCACHE(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARCACHE),
    .m_axi_mm_video_ARPROT(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARPROT),
    .m_axi_mm_video_ARQOS(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARQOS),
    .m_axi_mm_video_ARREGION(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARREGION),
    .m_axi_mm_video_ARUSER(AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARUSER),
    .m_axi_mm_video_RVALID(m_axi_mm_video_RVALID),
    .m_axi_mm_video_RREADY(AXIMMvideo2Bytes7_U0_m_axi_mm_video_RREADY),
    .m_axi_mm_video_RDATA(m_axi_mm_video_RDATA),
    .m_axi_mm_video_RLAST(m_axi_mm_video_RLAST),
    .m_axi_mm_video_RID(m_axi_mm_video_RID),
    .m_axi_mm_video_RUSER(m_axi_mm_video_RUSER),
    .m_axi_mm_video_RRESP(m_axi_mm_video_RRESP),
    .m_axi_mm_video_BVALID(1'b0),
    .m_axi_mm_video_BREADY(AXIMMvideo2Bytes7_U0_m_axi_mm_video_BREADY),
    .m_axi_mm_video_BRESP(2'd0),
    .m_axi_mm_video_BID(1'd0),
    .m_axi_mm_video_BUSER(1'd0),
    .bytePlanes1_din(AXIMMvideo2Bytes7_U0_bytePlanes1_din),
    .bytePlanes1_full_n(bytePlanes_plane0_full_n),
    .bytePlanes1_write(AXIMMvideo2Bytes7_U0_bytePlanes1_write),
    .srcImg(HwReg_frm_buffer),
    .p_read(p_read1),
    .p_read1(p_read4),
    .p_read2(p_read2),
    .p_read3(p_read),
    .p_read4(p_read3),
    .p_read5(p_read5),
    .Height_out_din(AXIMMvideo2Bytes7_U0_Height_out_din),
    .Height_out_full_n(height_c_full_n),
    .Height_out_write(AXIMMvideo2Bytes7_U0_Height_out_write),
    .WidthInBytes_out_din(AXIMMvideo2Bytes7_U0_WidthInBytes_out_din),
    .WidthInBytes_out_full_n(WidthInBytes_c_full_n),
    .WidthInBytes_out_write(AXIMMvideo2Bytes7_U0_WidthInBytes_out_write),
    .width_out_din(AXIMMvideo2Bytes7_U0_width_out_din),
    .width_out_full_n(width_c_full_n),
    .width_out_write(AXIMMvideo2Bytes7_U0_width_out_write),
    .video_format_out_din(AXIMMvideo2Bytes7_U0_video_format_out_din),
    .video_format_out_full_n(video_format_c_full_n),
    .video_format_out_write(AXIMMvideo2Bytes7_U0_video_format_out_write),
    .colorFormat_out_din(AXIMMvideo2Bytes7_U0_colorFormat_out_din),
    .colorFormat_out_full_n(colorFormat_c_full_n),
    .colorFormat_out_write(AXIMMvideo2Bytes7_U0_colorFormat_out_write)
);

system_v_frmbuf_rd_0_2_Bytes2MultiPixStream Bytes2MultiPixStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Bytes2MultiPixStream_U0_ap_start),
    .ap_done(Bytes2MultiPixStream_U0_ap_done),
    .ap_continue(Bytes2MultiPixStream_U0_ap_continue),
    .ap_idle(Bytes2MultiPixStream_U0_ap_idle),
    .ap_ready(Bytes2MultiPixStream_U0_ap_ready),
    .bytePlanes1_dout(bytePlanes_plane0_dout),
    .bytePlanes1_empty_n(bytePlanes_plane0_empty_n),
    .bytePlanes1_read(Bytes2MultiPixStream_U0_bytePlanes1_read),
    .img_din(Bytes2MultiPixStream_U0_img_din),
    .img_full_n(img_full_n),
    .img_write(Bytes2MultiPixStream_U0_img_write),
    .Height_dout(height_c_dout),
    .Height_empty_n(height_c_empty_n),
    .Height_read(Bytes2MultiPixStream_U0_Height_read),
    .Width_dout(width_c_dout),
    .Width_empty_n(width_c_empty_n),
    .Width_read(Bytes2MultiPixStream_U0_Width_read),
    .WidthInBytes_dout(WidthInBytes_c_dout),
    .WidthInBytes_empty_n(WidthInBytes_c_empty_n),
    .WidthInBytes_read(Bytes2MultiPixStream_U0_WidthInBytes_read),
    .VideoFormat_dout(video_format_c_dout),
    .VideoFormat_empty_n(video_format_c_empty_n),
    .VideoFormat_read(Bytes2MultiPixStream_U0_VideoFormat_read),
    .Height_out_din(Bytes2MultiPixStream_U0_Height_out_din),
    .Height_out_full_n(height_c9_full_n),
    .Height_out_write(Bytes2MultiPixStream_U0_Height_out_write),
    .Width_out_din(Bytes2MultiPixStream_U0_Width_out_din),
    .Width_out_full_n(width_c10_full_n),
    .Width_out_write(Bytes2MultiPixStream_U0_Width_out_write)
);

system_v_frmbuf_rd_0_2_MultiPixStream2AXIvideo MultiPixStream2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MultiPixStream2AXIvideo_U0_ap_start),
    .ap_done(MultiPixStream2AXIvideo_U0_ap_done),
    .ap_continue(MultiPixStream2AXIvideo_U0_ap_continue),
    .ap_idle(MultiPixStream2AXIvideo_U0_ap_idle),
    .ap_ready(MultiPixStream2AXIvideo_U0_ap_ready),
    .img_dout(img_dout),
    .img_empty_n(img_empty_n),
    .img_read(MultiPixStream2AXIvideo_U0_img_read),
    .m_axis_video_TDATA(MultiPixStream2AXIvideo_U0_m_axis_video_TDATA),
    .m_axis_video_TVALID(MultiPixStream2AXIvideo_U0_m_axis_video_TVALID),
    .m_axis_video_TREADY(m_axis_video_TREADY),
    .m_axis_video_TKEEP(MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB),
    .m_axis_video_TUSER(MultiPixStream2AXIvideo_U0_m_axis_video_TUSER),
    .m_axis_video_TLAST(MultiPixStream2AXIvideo_U0_m_axis_video_TLAST),
    .m_axis_video_TID(MultiPixStream2AXIvideo_U0_m_axis_video_TID),
    .m_axis_video_TDEST(MultiPixStream2AXIvideo_U0_m_axis_video_TDEST),
    .Height_dout(height_c9_dout),
    .Height_empty_n(height_c9_empty_n),
    .Height_read(MultiPixStream2AXIvideo_U0_Height_read),
    .WidthOut_dout(width_c10_dout),
    .WidthOut_empty_n(width_c10_empty_n),
    .WidthOut_read(MultiPixStream2AXIvideo_U0_WidthOut_read),
    .colorFormat_dout(colorFormat_c_dout),
    .colorFormat_empty_n(colorFormat_c_empty_n),
    .colorFormat_read(MultiPixStream2AXIvideo_U0_colorFormat_read)
);

system_v_frmbuf_rd_0_2_fifo_w64_d480_B bytePlanes_plane0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIMMvideo2Bytes7_U0_bytePlanes1_din),
    .if_full_n(bytePlanes_plane0_full_n),
    .if_write(AXIMMvideo2Bytes7_U0_bytePlanes1_write),
    .if_dout(bytePlanes_plane0_dout),
    .if_empty_n(bytePlanes_plane0_empty_n),
    .if_read(Bytes2MultiPixStream_U0_bytePlanes1_read)
);

system_v_frmbuf_rd_0_2_fifo_w11_d2_S height_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIMMvideo2Bytes7_U0_Height_out_din),
    .if_full_n(height_c_full_n),
    .if_write(AXIMMvideo2Bytes7_U0_Height_out_write),
    .if_dout(height_c_dout),
    .if_empty_n(height_c_empty_n),
    .if_read(Bytes2MultiPixStream_U0_Height_read)
);

system_v_frmbuf_rd_0_2_fifo_w14_d2_S WidthInBytes_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIMMvideo2Bytes7_U0_WidthInBytes_out_din),
    .if_full_n(WidthInBytes_c_full_n),
    .if_write(AXIMMvideo2Bytes7_U0_WidthInBytes_out_write),
    .if_dout(WidthInBytes_c_dout),
    .if_empty_n(WidthInBytes_c_empty_n),
    .if_read(Bytes2MultiPixStream_U0_WidthInBytes_read)
);

system_v_frmbuf_rd_0_2_fifo_w11_d2_S width_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIMMvideo2Bytes7_U0_width_out_din),
    .if_full_n(width_c_full_n),
    .if_write(AXIMMvideo2Bytes7_U0_width_out_write),
    .if_dout(width_c_dout),
    .if_empty_n(width_c_empty_n),
    .if_read(Bytes2MultiPixStream_U0_Width_read)
);

system_v_frmbuf_rd_0_2_fifo_w6_d2_S video_format_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIMMvideo2Bytes7_U0_video_format_out_din),
    .if_full_n(video_format_c_full_n),
    .if_write(AXIMMvideo2Bytes7_U0_video_format_out_write),
    .if_dout(video_format_c_dout),
    .if_empty_n(video_format_c_empty_n),
    .if_read(Bytes2MultiPixStream_U0_VideoFormat_read)
);

system_v_frmbuf_rd_0_2_fifo_w2_d3_S colorFormat_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIMMvideo2Bytes7_U0_colorFormat_out_din),
    .if_full_n(colorFormat_c_full_n),
    .if_write(AXIMMvideo2Bytes7_U0_colorFormat_out_write),
    .if_dout(colorFormat_c_dout),
    .if_empty_n(colorFormat_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_colorFormat_read)
);

system_v_frmbuf_rd_0_2_fifo_w24_d2_S img_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Bytes2MultiPixStream_U0_img_din),
    .if_full_n(img_full_n),
    .if_write(Bytes2MultiPixStream_U0_img_write),
    .if_dout(img_dout),
    .if_empty_n(img_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_img_read)
);

system_v_frmbuf_rd_0_2_fifo_w11_d2_S height_c9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Bytes2MultiPixStream_U0_Height_out_din),
    .if_full_n(height_c9_full_n),
    .if_write(Bytes2MultiPixStream_U0_Height_out_write),
    .if_dout(height_c9_dout),
    .if_empty_n(height_c9_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_Height_read)
);

system_v_frmbuf_rd_0_2_fifo_w11_d2_S width_c10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Bytes2MultiPixStream_U0_Width_out_din),
    .if_full_n(width_c10_full_n),
    .if_write(Bytes2MultiPixStream_U0_Width_out_write),
    .if_dout(width_c10_dout),
    .if_empty_n(width_c10_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_WidthOut_read)
);

system_v_frmbuf_rd_0_2_start_for_Bytes2MultiPixStream_U0 start_for_Bytes2MultiPixStream_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Bytes2MultiPixStream_U0_din),
    .if_full_n(start_for_Bytes2MultiPixStream_U0_full_n),
    .if_write(AXIMMvideo2Bytes7_U0_start_write),
    .if_dout(start_for_Bytes2MultiPixStream_U0_dout),
    .if_empty_n(start_for_Bytes2MultiPixStream_U0_empty_n),
    .if_read(Bytes2MultiPixStream_U0_ap_ready)
);

system_v_frmbuf_rd_0_2_start_for_MultiPixStream2AXIvideo_U0 start_for_MultiPixStream2AXIvideo_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_MultiPixStream2AXIvideo_U0_din),
    .if_full_n(start_for_MultiPixStream2AXIvideo_U0_full_n),
    .if_write(AXIMMvideo2Bytes7_U0_start_write),
    .if_dout(start_for_MultiPixStream2AXIvideo_U0_dout),
    .if_empty_n(start_for_MultiPixStream2AXIvideo_U0_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_ap_ready)
);

assign AXIMMvideo2Bytes7_U0_ap_continue = 1'b1;

assign AXIMMvideo2Bytes7_U0_ap_start = ap_start;

assign AXIMMvideo2Bytes7_U0_start_full_n = (start_for_MultiPixStream2AXIvideo_U0_full_n & start_for_Bytes2MultiPixStream_U0_full_n);

assign Bytes2MultiPixStream_U0_ap_continue = 1'b1;

assign Bytes2MultiPixStream_U0_ap_start = start_for_Bytes2MultiPixStream_U0_empty_n;

assign Bytes2MultiPixStream_U0_start_full_n = 1'b1;

assign Bytes2MultiPixStream_U0_start_write = 1'b0;

assign MultiPixStream2AXIvideo_U0_ap_continue = ap_continue;

assign MultiPixStream2AXIvideo_U0_ap_start = start_for_MultiPixStream2AXIvideo_U0_empty_n;

assign MultiPixStream2AXIvideo_U0_start_full_n = 1'b1;

assign MultiPixStream2AXIvideo_U0_start_write = 1'b0;

assign ap_done = MultiPixStream2AXIvideo_U0_ap_done;

assign ap_idle = (MultiPixStream2AXIvideo_U0_ap_idle & Bytes2MultiPixStream_U0_ap_idle & AXIMMvideo2Bytes7_U0_ap_idle);

assign ap_ready = AXIMMvideo2Bytes7_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = MultiPixStream2AXIvideo_U0_ap_done;

assign ap_sync_ready = AXIMMvideo2Bytes7_U0_ap_ready;

assign m_axi_mm_video_ARADDR = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARADDR;

assign m_axi_mm_video_ARBURST = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARBURST;

assign m_axi_mm_video_ARCACHE = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARCACHE;

assign m_axi_mm_video_ARID = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARID;

assign m_axi_mm_video_ARLEN = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARLEN;

assign m_axi_mm_video_ARLOCK = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARLOCK;

assign m_axi_mm_video_ARPROT = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARPROT;

assign m_axi_mm_video_ARQOS = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARQOS;

assign m_axi_mm_video_ARREGION = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARREGION;

assign m_axi_mm_video_ARSIZE = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARSIZE;

assign m_axi_mm_video_ARUSER = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARUSER;

assign m_axi_mm_video_ARVALID = AXIMMvideo2Bytes7_U0_m_axi_mm_video_ARVALID;

assign m_axi_mm_video_AWADDR = 32'd0;

assign m_axi_mm_video_AWBURST = 2'd0;

assign m_axi_mm_video_AWCACHE = 4'd0;

assign m_axi_mm_video_AWID = 1'd0;

assign m_axi_mm_video_AWLEN = 32'd0;

assign m_axi_mm_video_AWLOCK = 2'd0;

assign m_axi_mm_video_AWPROT = 3'd0;

assign m_axi_mm_video_AWQOS = 4'd0;

assign m_axi_mm_video_AWREGION = 4'd0;

assign m_axi_mm_video_AWSIZE = 3'd0;

assign m_axi_mm_video_AWUSER = 1'd0;

assign m_axi_mm_video_AWVALID = 1'b0;

assign m_axi_mm_video_BREADY = 1'b0;

assign m_axi_mm_video_RREADY = AXIMMvideo2Bytes7_U0_m_axi_mm_video_RREADY;

assign m_axi_mm_video_WDATA = 64'd0;

assign m_axi_mm_video_WID = 1'd0;

assign m_axi_mm_video_WLAST = 1'b0;

assign m_axi_mm_video_WSTRB = 8'd0;

assign m_axi_mm_video_WUSER = 1'd0;

assign m_axi_mm_video_WVALID = 1'b0;

assign m_axis_video_TDATA = MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;

assign m_axis_video_TDEST = MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;

assign m_axis_video_TID = MultiPixStream2AXIvideo_U0_m_axis_video_TID;

assign m_axis_video_TKEEP = MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;

assign m_axis_video_TLAST = MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;

assign m_axis_video_TSTRB = MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;

assign m_axis_video_TUSER = MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;

assign m_axis_video_TVALID = MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;

assign start_for_Bytes2MultiPixStream_U0_din = 1'b1;

assign start_for_MultiPixStream2AXIvideo_U0_din = 1'b1;

endmodule //system_v_frmbuf_rd_0_2_FrmbufRdHlsDataFlow
